# Mínimos Cuadrados Ordinarios (OLS) con statsmodels

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

# Agregar constante para el intercepto
X = sm.add_constant(X)

# Ajustar el modelo de regresión lineal
model = sm.OLS(y, X).fit()

# Resumen del modelo
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.991
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                     3476.
Date:                Mon, 27 May 2024   Prob (F-statistic):           9.50e-98
Time:                        16:25:45   Log-Likelihood:                 91.368
No. Observations:                 100   AIC:                            -174.7
Df Residuals:                      96   BIC:                            -164.3
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0253      0.031      0.808      0.4

# Regresión Ridge con Scikit-learn

In [2]:
from sklearn.linear_model import Ridge

In [3]:
# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

In [4]:
X.shape

(100, 3)

In [6]:
X[0:5,]

array([[0.97862189, 0.09915705, 0.76365889],
       [0.40007125, 0.24406113, 0.51238393],
       [0.43185611, 0.96666993, 0.48776408],
       [0.85556408, 0.67430735, 0.85305648],
       [0.90603038, 0.26760861, 0.90251989]])

In [7]:
y[0:5,]

array([2.18993742, 1.39977978, 3.75521734, 3.69585057, 2.48479629])

In [8]:
# Crear y ajustar el modelo de regresión Ridge
ridge = Ridge(alpha=1.0)
ridge.fit(X, y)

Ridge()

In [9]:
# Coeficientes del modelo
print(ridge.coef_)

[1.81927729 2.76265452 0.00451722]


In [10]:
prediccion = ridge.predict(X)

In [11]:
prediccion[0:5,]

array([2.26666301, 1.61330381, 3.66733655, 3.63213215, 2.60059967])

# Regresión Lasso con Scikit-learn

In [12]:
from sklearn.linear_model import Lasso

In [13]:
# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

In [14]:
# Crear y ajustar el modelo de regresión Lasso
lasso = Lasso(alpha=0.1)
lasso.fit(X, y)

Lasso(alpha=0.1)

In [15]:
# Coeficientes del modelo
print(lasso.coef_)

[ 0.48265155  1.44685969 -0.        ]


In [16]:
X[0:5,]

array([[0.34871362, 0.38032015, 0.78070574],
       [0.10036186, 0.44496039, 0.87524591],
       [0.86796024, 0.23162328, 0.50313038],
       [0.39089   , 0.9216433 , 0.8927068 ],
       [0.05195513, 0.52485   , 0.89360282]])

In [17]:
y[0:5,]

array([1.82380979, 1.48553009, 2.65118694, 3.69219398, 1.77568997])

In [18]:
pred_lasso = lasso.predict(X)
pred_lasso[0:5,]

array([2.17010943, 2.14376742, 2.20558111, 2.97368457, 2.2359929 ])

# Elastic Net con Scikit-learn

In [19]:
from sklearn.linear_model import ElasticNet

# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

# Crear y ajustar el modelo de regresión Elastic Net
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5)
elastic_net.fit(X, y)

# Coeficientes del modelo
print(elastic_net.coef_)

[1.07965326 1.55266664 0.        ]


In [20]:
pred_elastic = elastic_net.predict(X)

In [21]:
y[0:5,]

array([4.32443284, 2.68267635, 1.84099319, 4.20342798, 3.46183934])

In [22]:
pred_elastic[0:5,]

array([3.40457559, 2.61607343, 2.35028169, 3.35268366, 2.89174897])

# Descenso del Gradiente con Scikit-learn

In [23]:
from sklearn.linear_model import SGDRegressor

# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

# Crear y ajustar el modelo de regresión con descenso del gradiente
sgd = SGDRegressor(max_iter=1000, tol=1e-3)
sgd.fit(X, y)

# Coeficientes del modelo
print(sgd.coef_)

[ 1.45087859  2.07374354 -0.0068268 ]


In [24]:
pred_sgd = sgd.predict(X)

In [25]:
y[0:5,]

array([2.00694216, 2.56151188, 2.72765606, 3.1397565 , 3.15843334])

In [26]:
pred_sgd[0:5,]

array([2.14642488, 2.52922118, 2.69753855, 2.89381008, 2.92449593])