# Regresión Con Características Polinómicas

In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

# Datos de ejemplo
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)

# Crear un objeto PolynomialFeatures de grado 2
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

print(X_poly)

[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


In [2]:
from sklearn.linear_model import LinearRegression

# Variable dependiente
y = np.array([1, 4, 9, 16, 25])

# Ajustar el modelo de regresión lineal a las características polinómicas
model = LinearRegression()
model.fit(X_poly, y)

# Predicciones
y_pred = model.predict(X_poly)

In [3]:
from sklearn.metrics import mean_squared_error, r2_score

# Evaluación del modelo
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

print(f"MSE: {mse}, R2: {r2}")

MSE: 5.029974346915477e-29, R2: 1.0
