In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from tensorflow.keras.utils import to_categorical

In [2]:
# Datos de ejemplo
# Cada secuencia representa mediciones de actividad física (por ejemplo, pasos por minuto)
# Las etiquetas representan estados de salud: 0 para saludable y 1 para enfermo
X = [
    [10, 15, 10, 20, 15],  # actividad normal
    [30, 35, 30, 40, 35],  # actividad elevada
    [5, 5, 10, 5, 10],     # actividad reducida
    [20, 25, 20, 30, 25],  # actividad normal alta
    [5, 5, 5, 10, 5],      # actividad muy reducida
    [15, 20, 15, 25, 20]   # actividad normal
]
y = [0, 0, 1, 0, 1, 0]  # Etiquetas de estado de salud

In [3]:
X

[[10, 15, 10, 20, 15],
 [30, 35, 30, 40, 35],
 [5, 5, 10, 5, 10],
 [20, 25, 20, 30, 25],
 [5, 5, 5, 10, 5],
 [15, 20, 15, 25, 20]]

In [4]:
# Preprocesamiento de datos
# Ajuste de la forma de X para Keras: (número de muestras, pasos de tiempo, características)
X = np.array(X).reshape(len(X), 5, 1)  # 5 mediciones por secuencia, 1 característica por medición

In [5]:
X

array([[[10],
        [15],
        [10],
        [20],
        [15]],

       [[30],
        [35],
        [30],
        [40],
        [35]],

       [[ 5],
        [ 5],
        [10],
        [ 5],
        [10]],

       [[20],
        [25],
        [20],
        [30],
        [25]],

       [[ 5],
        [ 5],
        [ 5],
        [10],
        [ 5]],

       [[15],
        [20],
        [15],
        [25],
        [20]]])

In [6]:
# Convertir etiquetas y en formato categórico
y = to_categorical(y, num_classes=2)

In [7]:
y

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [8]:
# Construcción del modelo RNN (Red Neuronal Recurrente) para clasificación
model = Sequential()
model.add(LSTM(32, input_shape=(5, 1)))  # 32 unidades en la capa LSTM
model.add(Dense(2, activation='softmax'))  # Capa de salida para 2 clases
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
# Entrenamiento del modelo
model.fit(X, y, epochs=100, batch_size=1, verbose=1)

Epoch 1/100
6/6 [==============================] - 3s 10ms/step - loss: 1.0097 - accuracy: 0.3333
Epoch 2/100
6/6 [==============================] - 0s 9ms/step - loss: 0.8809 - accuracy: 0.3333
Epoch 3/100
6/6 [==============================] - 0s 8ms/step - loss: 0.7945 - accuracy: 0.3333
Epoch 4/100
6/6 [==============================] - 0s 15ms/step - loss: 0.7218 - accuracy: 0.3333
Epoch 5/100
6/6 [==============================] - 0s 14ms/step - loss: 0.6426 - accuracy: 1.0000
Epoch 6/100
6/6 [==============================] - 0s 14ms/step - loss: 0.5871 - accuracy: 1.0000
Epoch 7/100
6/6 [==============================] - 0s 10ms/step - loss: 0.5331 - accuracy: 0.8333
Epoch 8/100
6/6 [==============================] - 0s 23ms/step - loss: 0.4968 - accuracy: 0.8333
Epoch 9/100
6/6 [==============================] - 0s 11ms/step - loss: 0.4570 - accuracy: 0.8333
Epoch 10/100
6/6 [==============================] - 0s 10ms/step - loss: 0.4235 - accuracy: 0.8333
Epoch 11/100
6/6 [===

In [10]:
# Evaluación del modelo
accuracy = model.evaluate(X, y, verbose=0)[1]
print(f'Precisión del modelo: {accuracy * 100:.2f}%')

Precisión del modelo: 100.00%


In [12]:
model.predict([[[3],[3],[3],[5],[7]]])

1/1 [==============================] - 0s 40ms/step


array([[6.1947724e-04, 9.9938047e-01]], dtype=float32)